name: '[CI] ERD Generation Extension for StarUML v3'

on: [ push ]
#on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
#      - run: docker-compose -p mssql -f test/mssql/docker-compose.yml up -d db
#      - run: docker-compose -p postgresql -f test/postgresql/docker-compose.yml up -d db
#      - run: docker-compose -p mysql -f test/mysql/docker-compose.yml up -d db
      - run: >
          docker-compose -p mssql -f test/mssql/docker-compose.yml up -d db
          && docker-compose -p postgresql -f test/postgresql/docker-compose.yml up -d db
          && docker-compose -p mysql -f test/mysql/docker-compose.yml up -d db
          && nc -zv -w 30 localhost 1433
          && nc -zv -w 30 localhost 5432
          && nc -zv -w 30 localhost 3306
          && npm test
#      - run: docker-compose -f test/mssql/docker-compose.yml down
#      - run: docker-compose -f test/postgresql/docker-compose.yml down
#      - run: docker-compose -f test/mysql/docker-compose.yml down
      - run: npm run coveralls
