name: 'github-actions-build'

on: [ push ]
#on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      ## test ##
      - name: Run MS SQL
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: test/mssql/docker-compose.yml
          composeArguments: -d
          serviceName: db
      - name: Run Postgre SQL
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: test/postgresql/docker-compose.yml
          composeArguments: -d
          serviceName: db
      - name: Run MySQL
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: test/mysql/docker-compose.yml
          composeArguments: -d
          serviceName: db
      - run: nc -zv -w 30 localhost 1433
      - run: nc -zv -w 30 localhost 5432
      - run: nc -zv -w 30 localhost 3306
      # temp solution
      - run: sleep 120
      - run: npm test

  report:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
