name: '[CI] ERD Generation Extension for StarUML v3'

on: [ push ]
#on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:
#  container-job:
#    # Containers must run in Linux based operating systems
#    runs-on: ubuntu-latest
#    # Docker Hub image that `container-job` executes in
#    container: node:16-bullseye
#
#    # Service containers to run with `container-job`
#    services:
#      # Label used to access the service container
#      databases:
#        # Docker Hub image
#        image: docker:20.10.17-dind-alpine3.16

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: MS SQL | Test with docker-compose
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: test/mssql/docker-compose.yml
          serviceName: db
#      - run: nc -zv -w 30 localhost 1433
      - name: Postgre SQL | Test with docker-compose
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: test/postgresql/docker-compose.yml
          composeArguments: -d
          serviceName: db
#      - run: nc -zv -w 30 localhost 5432 && echo "OK" || echo "FAILED"
      - name: MySQL | Test with docker-compose
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: test/mysql/docker-compose.yml
          serviceName: db
#      - run: nc -zv -w 30 localhost 3306
      - run: sudo apt-get install -y postgresql-client
      - run: PGPASSWORD=password PGSSLMODE=disable psql -h 127.0.0.1 -U user -d user -c 'SELECT 1'
      - run: npm test
      - run: npm run coveralls
